### ISSUE TITLE
超过1GB，github不让下载，连zip也不行。

### ISSUE THREAD

**Issue by monkeyDsam** [jiajunlong/zhoujielun#1]
虽然我fork了，但是我一直没有找到下载这些歌曲的方法。
使用了 git clone   ，迅雷 ,wget 等工具。

**Comment by monkeyDsam** [comment]
> 虽然我fork了，但是我一直没有找到下载这些歌曲的方法。 使用了 git clone ，迅雷 ,wget 等工具。

**Comment by jiajunlong** [comment]
没考虑过这个，我直接给你发压缩文件算了，解压到同一个文件夹里就可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiajunlong/zhoujielun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月17日(星期一) 上午10:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[jiajunlong/zhoujielun] 超过1GB，github不让下载，连zip也不行。 (Issue #1)





 
虽然我fork了，但是我一直没有找到下载这些歌曲的方法。
 使用了 git clone   ，迅雷 ,wget 等工具。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

周杰伦.part1.rar (720.00M, 2022年02月16日 21:27 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=70633433643031ebc6d01072423003170c5055065607030918000502511d050a505a190b520008155456570b0501500a56565507642031eee9dee8f1b31e41594717051d1651433808&code=5c43d018




周杰伦.part2.rar (699.53M, 2022年02月16日 21:27 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7c343033f3b375edca871472143100165c0d005150535101145206070a1c06005b501d52030554145f50560a025550010803520b322132efe589ecf1e51f42584b40021d4050403904&code=94032129
